- README.md
> Add Render deployment guide

- README.md
Added my Mozilla WoT gateway addon for gotify
> Mozilla WoT Gateway Addon for gotify

- README.md
> Add gotify-slack plugin

- README.md
> Add tutorial to setup

- README.md
```
- [mrspartak/gotify-dc](https://github.com/mrspartak/gotify-dc) - Docker-compose config to help deploy with nginx.
```
> Added docker compose repository

- README.md
- [x ] Your submissions have the following format:
```
- [cyrinux/imap2gotify](https://github.com/cyrinux/imap2gotify) An Emails IMAP Idle proxy to `gotify/server`.
```
- [x ] Your additions are ordered alphabetically.
> Add cyrinux/imap2gotify

- README.md
Nagios plugin to send notification via Gotify
```
```
> Add contribution

- README.md
> Add GitHub action

- README.md
> Add gotify-dunst client

- README.md
Project source code: https://gitlab.com/rakshazi/desktop2gotify
> added desktop2gotify

- README.md
Add [diddypod/rotify](https://github.com/diddypod/rotify) - Send and view Gotify messages via rofi
> Add diddypod/rotify - rofi script

- README.md
Adds my gotify-smtp plugin to the list.
```
```
> Add plugin tystuyfzand/gotify-smtp

- README.md
The [gotify matrix bot](https://github.com/Ondolin/gotify-matrix-bot) is a small tool to recive gotify messages in a matrix chat.
> Gotify matrix bot

- README.md
The checker is a bash script that will push notifications for running docker images updates to your gotify server.
> Added methatronc/checker in Scripts

- README.md
I added a small tool I just created to help me receive notifications from sources that don't support Gotify.
> Added mattmckenzy/mail2gotify to README

- README.md
> Added gotify-emailer plugin to the contrib

- README.md
Added link for gotify-fox. Addresses #34
> Update README.md  with Gotify-fox

- README.md
> added Python module

- README.md
```
```
A while ago I modified a script for sending Pushbullet notifications from email to work with gotify, and thought it should probably be listed here. It's intended to be used on a server where you have a local postfix install and want a more convenient way to monitor system emails, especially for things like cron jobs. It's similar to the [mail2gotify](https://github.com/MattMckenzy/Mail2Gotify) project listed here but is designed to be used with an existing mail server.
Cheers
> Add email2gotify script

- README.md
```
- [AmamiyaHotaru/GotifyToESPDeerAdapter](https://github.com/AmamiyaHotaru/GotifyToESPDeerAdapter) A plugin for forwarding Gotify messages to MQTT for compatibility with Deeresp (Pushdeer's IoT version)
```
> add AmamiyaHotaru/GotifyToESPDeerAdapter

- README.md
Hi i created a Bridge for iOS with a C# Docker container that listening to the websocket and send a Push Notification to iOS devices after download the App from the AppStore
> Added iGotify-Notification-Assistent

- README.md
> Add hywax/gotify-client

- README.md
> Gotify2telegram

- README.md
> Add MexHigh/Gotify-Webhooks-Plugin

- README.md
Adds a NATS to gotify plugin
```
```
> Adds thomas-maurice/gotify-nats-plugin

- README.md
> Added my Projects

- README.md
> Add gotify-alertmanager-plugin

- README.md
> Add Gotify Gnome desktop client

- README.md
> Add gotify-smtp-emailer plugin

- README.md
```
- [ckocyigit/gotify-authentik-plugin](https://github.com/ckocyigit/gotify-authentik-plugin) A plugin that allows gotify/server to directly receive and process webhooks from [Authentik](https://github.com/goauthentik/authentik).
```
> Add ckocyigit/gotify-authentik-plugin

- README.md
> Add github.com/eternal-flame-AD/gotify-webhook-misskey

- README.md
> Add JakobST1n/RSS-watcher to Tools list

- README.md
> Add MexHigh/Gotify-Postal-Webhooks-Plugin to Plugins list

- README.md
> Add cyb3rko/gotify-mtls-setup

- README.md
```
```
- Tested it, works fine
> Add 'CrowdSec Notification Plugin'
